### ISSUE TITLE
Docs use wrong Maven repo and wrong Gradle syntax

### ISSUE THREAD

**Issue by translatenix** [apple/pkl-lang.org#10]
Example: https://pkl-lang.org/main/current/pkl-core/index.html#gradle

Is:
```
dependencies {
  compile "org.pkl-lang:pkl-core:0.25.2"
}

repositories {
  maven { url "https://s01.oss.sonatype.org/content/groups/public" }
}
```

Should be:
```
dependencies {
  implementation "org.pkl-lang:pkl-core:0.25.2"
}

repositories {
  mavenCentral()
}
```

 `compile` was replaced with `implementation` long ago and might no longer work at this point.
 
 Gradle snippets should use `mavenCentral()`. Maven snippets don't need a repo because Maven Central is the default.

PS: I tried to come up with a permalink for https://pkl-lang.org/main/current/pkl-core/index.html, but replacing `current` with `0.25.2` didn't work.

**Comment by madrob** [comment]
I believe this was fixed in https://github.com/apple/pkl/pull/106 and https://github.com/apple/pkl/pull/210
