### ISSUE TITLE
Hamburger button not working on mobile

### ISSUE THREAD

**Issue by zachspiel** [apple/pkl-lang.org#9]
https://github.com/apple/pkl-lang.org/assets/20634543/208f8fd2-4f46-4a61-b841-2a690070367c

**Comment by HermanBide** [comment]
Has this issue been resolved ?

**Comment by holzensp** [comment]
Not yet, I'm afraid. It's reproducible on desktop with a narrow browser window.

**Comment by stackoverflow** [comment]
There's a PR open to fix it. Shouldn't take long.

**Comment by holzensp** [comment]
Merged PR and confirmed fixed on mobile. Still malfunctioning on narrow-browser desktop, though.

**Comment by HermanBide** [comment]
okay i was looking to contribute.
